name = "bfm_rep"
uuid = "959a3547-8733-4ae5-b3c5-88de57bae10f"
authors = ["Cassi <cassidkirkland@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
